### ISSUE TITLE
Failed conda installation of reaktoro in macOS

### ISSUE THREAD

**Issue by mtsveta** [reaktoro/reaktoro#73]
conda install -c conda-forge/label/gcc7 reaktoro 
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - reaktoro

Current channels:

  - https://conda.anaconda.org/conda-forge/label/gcc7/osx-64
  - https://conda.anaconda.org/conda-forge/label/gcc7/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by allanleal** [comment]
There is no such label `conda-forge/label/gcc7` anymore. The docs were updated by @nicoddemus some time ago, but I forgot to update the website with the new changes. Doing it now.

**Comment by allanleal** [comment]
Done.

**Comment by allanleal** [comment]
Looks like the error is actually related to no macOS reaktoro package on conda-forge. Something that should be soon supported, now that @alexandrebbruno has fixed all regression tests failing in macOS.

@tehrengruber Those regression tests were fixed. Let me know your availability to proceed with macOS support in conda-forge now (also add CI on github for macOS).

**Comment by dawnine** [comment]
Problem mentioned by @mtsveta is still existed when using anaconda with macOS ‎Mojave. Hope that will be solved.

**Comment by allanleal** [comment]
As of early today, we can now install Reaktoro in macOS using `conda install reaktoro` (or `conda install conda-forge::reaktoro` if the `conda-forge` channel has not yet been appended to the list of channels that conda uses to search for packages). Before, this conda installation support only existed for Windows and Linux.
